In [297]:
import pandas as pd
import numpy as np

pd.set_option('display.float_format', lambda x: '%.2f' % x)

def contar_nulos(df, columna):
    """
    Cuenta y muestra los valores faltantes en una columna 
    """
    total_nulos = df[columna].isnull().sum()
    print(f"Valores faltantes en {columna}: {total_nulos}")
    return total_nulos

def analizar_columna(df, columna):
    """
    Muestra estadísticas descriptivas y conteo de valores para una columna
    """
    print(f"--- Resumen de: {columna} ---")
    print("\n📊 Estadísticas Descriptivas:")
    print(df[columna].describe())
    
    print("\n🔢 Conteo de Valores (Frecuencias):")
    print(df[columna].value_counts())
    print("-" * 30)





# Limpieza Demo_H

In [298]:
df = pd.read_csv("../data/interim/demo_h_columnas.csv")

mapeo_nombres = {
    "SEQN": "ID",
    "RIAGENDR": "Genero",
    "RIDAGEYR": "Edad",
    "RIDRETH3": "Etnia",
    "DMDEDUC2": "Nivel_Educativo",
    "DMDMARTL": "Estado_Civil",
    "INDFMPIR": "Ratio_Pobreza",
    "DMQMILIZ": "Servicio_Militar",
}

df = df.rename(columns=mapeo_nombres)

df = df[df["Edad"] >= 18]

df.head()

,ID,Genero,Edad,Etnia,Nivel_Educativo,Estado_Civil,Ratio_Pobreza,Servicio_Militar
0,73557.00,1.00,69.00,4.00,3.00,4.00,0.84,1.00
1,73558.00,1.00,54.00,3.00,3.00,1.00,1.78,2.00
2,73559.00,1.00,72.00,3.00,4.00,1.00,4.51,1.00
4,73561.00,2.00,73.00,3.00,5.00,1.00,5.00,2.00
5,73562.00,1.00,56.00,1.00,4.00,3.00,4.79,1.00


### Mapeo de numeros a columnas (opcional) (one-hot enconding)

In [299]:
### Mapeo de numeros a columnas (opcional) (one-hot enconding)

""" mapeo_etnia = {
    1: "Mexicano_Americano",
    2: "Otro_Hispano",
    3: "Blanco_No_Hispano",
    4: "Negro_No_Hispano",
    6: "Asiatico_No_Hispano",
    7: "Otra_Raza_Multi"
}

df['Etnia'] = df['Etnia'].map(mapeo_etnia)

# mapeo de atributos a columnas True o False
df = pd.get_dummies(df, columns=['Etnia'], prefix='Etnia')

df.head() """

' mapeo_etnia = {\n    1: "Mexicano_Americano",\n    2: "Otro_Hispano",\n    3: "Blanco_No_Hispano",\n    4: "Negro_No_Hispano",\n    6: "Asiatico_No_Hispano",\n    7: "Otra_Raza_Multi"\n}\n\ndf[\'Etnia\'] = df[\'Etnia\'].map(mapeo_etnia)\n\n# mapeo de atributos a columnas True o False\ndf = pd.get_dummies(df, columns=[\'Etnia\'], prefix=\'Etnia\')\n\ndf.head() '

## Limpieza de edad

### Revisar nulos

In [300]:
total_nulos = df['Edad'].isnull().sum()
print(f"Valores faltantes en Edad: {total_nulos}")

Valores faltantes en Edad: 0


### Convertir floats a enteros

In [301]:
df["Edad"] = df["Edad"].apply(np.floor).astype("Int64")
df["Edad"] = df["Edad"].astype("Int64")
# porcentajes
df["Edad"].value_counts(normalize=True) * 100


Edad
80   5.76
18   3.12
19   2.50
63   1.95
30   1.91
     ... 
76   0.83
75   0.83
77   0.62
78   0.59
79   0.49
Name: proportion, Length: 63, dtype: Float64

In [302]:
df["Edad"].describe()


count   6113.00
mean      47.39
std       18.47
min       18.00
25%       32.00
50%       47.00
75%       62.00
max       80.00
Name: Edad, dtype: Float64

## Limpieza de Nivel_Educativo



In [303]:
contar_nulos(df,"Nivel_Educativo")

print(df["Nivel_Educativo"].value_counts())


Valores faltantes en Nivel_Educativo: 344
Nivel_Educativo
4.00    1770
5.00    1443
3.00    1303
2.00     791
1.00     455
9.00       5
7.00       2
Name: count, dtype: int64


## Limpieza de Estado_Civil

In [304]:
analizar_columna(df,"Estado_Civil")

--- Resumen de: Estado_Civil ---

📊 Estadísticas Descriptivas:
count   5769.00
mean       2.57
std        2.63
min        1.00
25%        1.00
50%        1.00
75%        5.00
max       99.00
Name: Estado_Civil, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Estado_Civil
1.00     2965
5.00     1112
3.00      659
2.00      436
6.00      417
4.00      177
77.00       2
99.00       1
Name: count, dtype: int64
------------------------------


In [305]:
contar_nulos(df,"Estado_Civil")

Valores faltantes en Estado_Civil: 344


np.int64(344)

### Limpiar nulos y 77, 99

In [306]:
# Reemplazar los valores 77 y 99 por 5 (nunca casado)
df["Estado_Civil"] = df["Estado_Civil"].replace({77.0: 5, 99.0: 5})

In [307]:
analizar_columna(df,"Estado_Civil")


--- Resumen de: Estado_Civil ---

📊 Estadísticas Descriptivas:
count   5769.00
mean       2.53
std        1.83
min        1.00
25%        1.00
50%        1.00
75%        5.00
max        6.00
Name: Estado_Civil, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Estado_Civil
1.00    2965
5.00    1115
3.00     659
2.00     436
6.00     417
4.00     177
Name: count, dtype: int64
------------------------------


## Limpieza de Servicio_Militar

In [308]:
analizar_columna(df,"Servicio_Militar")

--- Resumen de: Servicio_Militar ---

📊 Estadísticas Descriptivas:
count   6113.00
mean       1.91
std        0.29
min        1.00
25%        2.00
50%        2.00
75%        2.00
max        7.00
Name: Servicio_Militar, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Servicio_Militar
2.00    5569
1.00     543
7.00       1
Name: count, dtype: int64
------------------------------


In [309]:
contar_nulos(df,"Servicio_Militar")

Valores faltantes en Servicio_Militar: 0


np.int64(0)

In [310]:
# Reemplazar los valores 7 por 2 (No)
df["Servicio_Militar"] = df["Servicio_Militar"].replace({7: 2})

## Limpieza de Ratio Pobreza


In [311]:
analizar_columna(df,'Ratio_Pobreza')

--- Resumen de: Ratio_Pobreza ---

📊 Estadísticas Descriptivas:
count   5628.00
mean       2.45
std        1.65
min        0.00
25%        1.02
50%        2.02
75%        3.95
max        5.00
Name: Ratio_Pobreza, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Ratio_Pobreza
5.00    1013
1.27      79
0.00      53
0.86      50
1.29      44
        ... 
1.90       1
3.11       1
2.17       1
4.50       1
3.90       1
Name: count, Length: 425, dtype: int64
------------------------------


In [312]:
contar_nulos(df,'Ratio_Pobreza')

Valores faltantes en Ratio_Pobreza: 485


np.int64(485)

#### No rellenar con nulos

Rellnar los nulos con 0 no es correcto, puesto que los nulos son falta de informacion y 0 tiene un significado real.  

INDFMPIR: This variable is the ratio of family income to poverty. The Department of Health and Human Services (HHS) poverty guidelines were used as the poverty measure to calculate this ratio. These guidelines are issued each year, in the Federal Register, for determining financial eligibility for certain federal programs, such as Head Start, Supplemental Nutrition Assistance Program (SNAP), Special Supplemental Nutrition Program for Women, Infants, and Children (WIC), and the National School Lunch Program. The poverty guidelines vary by family size and geographic location (with different guidelines for the 48 contiguous states and the District of Columbia; Alaska; and Hawaii).

INDFMPIR was calculated by dividing family (or individual) income by the poverty guidelines specific to the survey year. The value was not computed if the respondent only reported income as < $20,000 or ≥ $20,000. If family income was reported as a more detailed category, the midpoint of the range was used to compute the ratio. Values at or above 5.00 were coded as 5.00 or more because of disclosure concerns. The values were not computed if the income data was missing.

In [313]:
# Crear una columna bandera (1 si era nulo, 0 si no)
df["Ratio_Pobreza_Faltante"] = df["Ratio_Pobreza"].isnull().astype(int)

In [314]:
# Rellenar el nulo con la mediana
mediana_pobreza = df["Ratio_Pobreza"].median()
df["Ratio_Pobreza"] = df["Ratio_Pobreza"].fillna(mediana_pobreza)

In [315]:
analizar_columna(df,'Ratio_Pobreza')

--- Resumen de: Ratio_Pobreza ---

📊 Estadísticas Descriptivas:
count   6113.00
mean       2.42
std        1.59
min        0.00
25%        1.06
50%        2.02
75%        3.81
max        5.00
Name: Ratio_Pobreza, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Ratio_Pobreza
5.00    1013
2.02     505
1.27      79
0.00      53
0.86      50
        ... 
1.90       1
3.11       1
2.17       1
4.50       1
3.90       1
Name: count, Length: 425, dtype: int64
------------------------------


# Limpieza ALQ

In [316]:
df = pd.read_csv("../data/interim/alq_h_columnas.csv")

nuevos_nombres = {
    "ALQ120Q": "Frec_Consumo_Anual",
    "ALQ120U": "Unidad_Frec_Anual",
    "ALQ130":  "Promedio_Tragos_Dia",
    "ALQ141Q": "Dias_4_5_Tragos",
    "ALQ141U": "Unidad_4_5_Tragos", 
    "ALQ160":  "Dias_Con_+4_5_Tragos_En_2hrs"
}

# Aplicar el cambio
df = df.rename(columns=nuevos_nombres)
df.head()


,SEQN,ALQ101,ALQ110,Frec_Consumo_Anual,Unidad_Frec_Anual,Promedio_Tragos_Dia,Dias_4_5_Tragos,Unidad_4_5_Tragos,Dias_Con_+4_5_Tragos_En_2hrs
0,73557.00,1.00,NaN,1.00,3.00,1.00,0.00,NaN,NaN
1,73558.00,1.00,NaN,7.00,1.00,4.00,2.00,1.00,0.00
2,73559.00,1.00,NaN,0.00,NaN,NaN,NaN,NaN,NaN
3,73561.00,1.00,NaN,0.00,NaN,NaN,NaN,NaN,NaN
4,73562.00,1.00,NaN,5.00,3.00,1.00,0.00,NaN,0.00


In [317]:
# Marcar 0s en columnas relevantes para personas que no han consumido alcohol

# Redondear 
df['Frec_Consumo_Anual'] = df['Frec_Consumo_Anual'].round(2)
df['Dias_4_5_Tragos'] = df['Dias_4_5_Tragos'].round(2)
df['Dias_Con_+4_5_Tragos_En_2hrs'] = df['Dias_Con_+4_5_Tragos_En_2hrs'].round(2)


# Creamos una columna si ha consumido alcohol en toda su vida
df['Consumio_Alcohol'] = ((df['ALQ101'] == 1) | (df['ALQ110'] == 1)) & (df['Frec_Consumo_Anual'] > 0)


# Definimos la lista de columnas que queremos poner en 0
columnas_relevantes = [
    "Frec_Consumo_Anual",
    "Unidad_Frec_Anual",
    "Promedio_Tragos_Dia",
    "Dias_4_5_Tragos",
    "Unidad_4_5_Tragos", 
    "Dias_Con_+4_5_Tragos_En_2hrs"
]


# Si 'Consumio_Alcohol' es False, asignamos 0 a todas esas columnas
df.loc[df['Consumio_Alcohol'] == False, columnas_relevantes] = 0

df

,SEQN,ALQ101,ALQ110,Frec_Consumo_Anual,Unidad_Frec_Anual,Promedio_Tragos_Dia,Dias_4_5_Tragos,Unidad_4_5_Tragos,Dias_Con_+4_5_Tragos_En_2hrs,Consumio_Alcohol
0,73557.00,1.00,NaN,1.00,3.00,1.00,0.00,NaN,NaN,True
1,73558.00,1.00,NaN,7.00,1.00,4.00,2.00,1.00,0.00,True
2,73559.00,1.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,False
3,73561.00,1.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,False
4,73562.00,1.00,NaN,5.00,3.00,1.00,0.00,NaN,0.00,True
...,...,...,...,...,...,...,...,...,...,...
5919,83723.00,1.00,NaN,3.00,3.00,2.00,0.00,NaN,NaN,True
5920,83724.00,1.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,False
5921,83726.00,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,False
5922,83727.00,1.00,NaN,1.00,2.00,3.00,0.00,NaN,NaN,True


In [318]:
analizar_columna(df,'Consumio_Alcohol')
contar_nulos(df,'Consumio_Alcohol')

--- Resumen de: Consumio_Alcohol ---

📊 Estadísticas Descriptivas:
count     5924
unique       2
top       True
freq      3597
Name: Consumio_Alcohol, dtype: object

🔢 Conteo de Valores (Frecuencias):
Consumio_Alcohol
True     3597
False    2327
Name: count, dtype: int64
------------------------------
Valores faltantes en Consumio_Alcohol: 0


np.int64(0)

Crearemos una sola columna Dias_Consumo_Anual para unir la frecuencia y el consumo

### Limpieza de Frec_Consumo_Anual, Mantenemos nulos


In [319]:
analizar_columna(df,'Frec_Consumo_Anual')
contar_nulos(df,'Frec_Consumo_Anual')

--- Resumen de: Frec_Consumo_Anual ---

📊 Estadísticas Descriptivas:
count   5924.00
mean       3.56
std       30.00
min        0.00
25%        0.00
50%        1.00
75%        3.00
max      999.00
Name: Frec_Consumo_Anual, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Frec_Consumo_Anual
0.00      2327
1.00      1046
2.00       884
3.00       524
4.00       302
5.00       265
7.00       194
6.00       141
10.00       70
20.00       24
12.00       24
8.00        23
15.00       22
30.00       20
14.00        6
365.00       6
9.00         4
999.00       4
25.00        4
24.00        4
40.00        2
80.00        2
11.00        2
16.00        2
100.00       2
28.00        2
52.00        1
200.00       1
90.00        1
300.00       1
18.00        1
350.00       1
17.00        1
305.00       1
182.00       1
45.00        1
160.00       1
96.00        1
13.00        1
112.00       1
61.00        1
180.00       1
120.00       1
35.00        1
Name: count, dtype: int64
---------------------

np.int64(0)

In [320]:
dont_know = df[df['Frec_Consumo_Anual']==999]
dont_know

,SEQN,ALQ101,ALQ110,Frec_Consumo_Anual,Unidad_Frec_Anual,Promedio_Tragos_Dia,Dias_4_5_Tragos,Unidad_4_5_Tragos,Dias_Con_+4_5_Tragos_En_2hrs,Consumio_Alcohol
104,73726.00,1.00,NaN,999.00,NaN,1.00,0.00,NaN,NaN,True
561,74542.00,1.00,NaN,999.00,NaN,3.00,0.00,NaN,NaN,True
3544,79688.00,1.00,NaN,999.00,NaN,999.00,0.00,NaN,NaN,True
5276,82616.00,1.00,NaN,999.00,NaN,4.00,999.00,NaN,NaN,True


Existen 4 personas con 999 (Don't Know), por simplicidad las eliminaremos del dataset.
No podemos decir que no consumen alchool porque tienen valores en 
Promedio Tragos Dia

In [321]:
# Filtramos el dataframe para excluir las filas con 999
df = df[df['Frec_Consumo_Anual'] != 999]

# Reseteamos el índice para mantener el orden
df = df.reset_index(drop=True)

In [322]:
analizar_columna(df,'Frec_Consumo_Anual')
contar_nulos(df,'Frec_Consumo_Anual')

--- Resumen de: Frec_Consumo_Anual ---

📊 Estadísticas Descriptivas:
count   5920.00
mean       2.89
std       15.19
min        0.00
25%        0.00
50%        1.00
75%        3.00
max      365.00
Name: Frec_Consumo_Anual, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Frec_Consumo_Anual
0.00      2327
1.00      1046
2.00       884
3.00       524
4.00       302
5.00       265
7.00       194
6.00       141
10.00       70
20.00       24
12.00       24
8.00        23
15.00       22
30.00       20
14.00        6
365.00       6
9.00         4
25.00        4
24.00        4
40.00        2
80.00        2
11.00        2
16.00        2
100.00       2
28.00        2
52.00        1
200.00       1
90.00        1
300.00       1
18.00        1
350.00       1
17.00        1
305.00       1
182.00       1
45.00        1
160.00       1
96.00        1
13.00        1
112.00       1
61.00        1
180.00       1
120.00       1
35.00        1
Name: count, dtype: int64
------------------------------
Valor

np.int64(0)

### Limpieza de Unidad_Frec_Anual

In [323]:
analizar_columna(df,'Unidad_Frec_Anual')
contar_nulos(df,'Unidad_Frec_Anual')

--- Resumen de: Unidad_Frec_Anual ---

📊 Estadísticas Descriptivas:
count   5920.00
mean       1.17
std        1.15
min        0.00
25%        0.00
50%        1.00
75%        2.00
max        3.00
Name: Unidad_Frec_Anual, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Unidad_Frec_Anual
0.00    2327
1.00    1461
3.00    1179
2.00     953
Name: count, dtype: int64
------------------------------
Valores faltantes en Unidad_Frec_Anual: 0


np.int64(0)

### Creacion de Dias_Consumo_Anual

In [324]:
factores = {1: 52, 2: 12, 3: 1}
df['Dias_Consumo_Anual'] = df['Frec_Consumo_Anual'] * df['Unidad_Frec_Anual'].map(factores)

# Como los que marcaron 0 no tienen unidad, el resultado da NaN, pero debería ser 0.
df.loc[df['Frec_Consumo_Anual'] == 0, 'Dias_Consumo_Anual'] = 0

analizar_columna(df,'Dias_Consumo_Anual')
contar_nulos(df,'Dias_Consumo_Anual')
df

--- Resumen de: Dias_Consumo_Anual ---

📊 Estadísticas Descriptivas:
count   5920.00
mean      43.64
std       82.69
min        0.00
25%        0.00
50%        4.00
75%       52.00
max      365.00
Name: Dias_Consumo_Anual, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Dias_Consumo_Anual
0.00      2327
52.00      442
12.00      421
104.00     353
24.00      321
156.00     250
2.00       214
1.00       206
3.00       169
364.00     167
4.00       138
5.00       121
260.00     114
208.00     105
36.00      105
6.00       100
10.00       64
48.00       59
312.00      31
60.00       30
20.00       22
7.00        21
8.00        20
30.00       18
15.00       18
72.00       10
120.00       7
84.00        6
365.00       6
180.00       5
300.00       4
14.00        4
9.00         4
96.00        4
40.00        2
240.00       2
16.00        2
360.00       2
144.00       2
80.00        2
100.00       2
168.00       2
216.00       1
200.00       1
45.00        1
90.00        1
25.00        1
35

,SEQN,ALQ101,ALQ110,Frec_Consumo_Anual,Unidad_Frec_Anual,Promedio_Tragos_Dia,Dias_4_5_Tragos,Unidad_4_5_Tragos,Dias_Con_+4_5_Tragos_En_2hrs,Consumio_Alcohol,Dias_Consumo_Anual
0,73557.00,1.00,NaN,1.00,3.00,1.00,0.00,NaN,NaN,True,1.00
1,73558.00,1.00,NaN,7.00,1.00,4.00,2.00,1.00,0.00,True,364.00
2,73559.00,1.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,False,0.00
3,73561.00,1.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,False,0.00
4,73562.00,1.00,NaN,5.00,3.00,1.00,0.00,NaN,0.00,True,5.00
...,...,...,...,...,...,...,...,...,...,...,...
5915,83723.00,1.00,NaN,3.00,3.00,2.00,0.00,NaN,NaN,True,3.00
5916,83724.00,1.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,False,0.00
5917,83726.00,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,False,0.00
5918,83727.00,1.00,NaN,1.00,2.00,3.00,0.00,NaN,NaN,True,12.00


In [325]:
df[df['Dias_Consumo_Anual']==364]

,SEQN,ALQ101,ALQ110,Frec_Consumo_Anual,Unidad_Frec_Anual,Promedio_Tragos_Dia,Dias_4_5_Tragos,Unidad_4_5_Tragos,Dias_Con_+4_5_Tragos_En_2hrs,Consumio_Alcohol,Dias_Consumo_Anual
1,73558.00,1.00,NaN,7.00,1.00,4.00,2.00,1.00,0.00,True,364.00
33,73618.00,1.00,NaN,7.00,1.00,1.00,0.00,NaN,NaN,True,364.00
70,73672.00,1.00,NaN,7.00,1.00,2.00,1.00,3.00,0.00,True,364.00
100,73722.00,1.00,NaN,7.00,1.00,1.00,0.00,NaN,NaN,True,364.00
106,73732.00,1.00,NaN,7.00,1.00,2.00,0.00,NaN,NaN,True,364.00
...,...,...,...,...,...,...,...,...,...,...,...
5823,83569.00,1.00,NaN,7.00,1.00,2.00,0.00,NaN,NaN,True,364.00
5827,83578.00,1.00,NaN,7.00,1.00,1.00,4.00,3.00,0.00,True,364.00
5836,83592.00,1.00,NaN,7.00,1.00,1.00,1.00,1.00,0.00,True,364.00
5887,83678.00,1.00,NaN,7.00,1.00,10.00,7.00,1.00,0.00,True,364.00


### Limpieza Promedio_Tragos Dia

In [326]:
analizar_columna(df,'Promedio_Tragos_Dia')
contar_nulos(df,'Promedio_Tragos_Dia')

--- Resumen de: Promedio_Tragos_Dia ---

📊 Estadísticas Descriptivas:
count   5919.00
mean       1.96
std       18.47
min        0.00
25%        0.00
50%        1.00
75%        2.00
max      999.00
Name: Promedio_Tragos_Dia, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Promedio_Tragos_Dia
0.00      2327
1.00      1279
2.00      1002
3.00       535
4.00       282
6.00       156
5.00       154
8.00        54
12.00       43
10.00       28
7.00        23
15.00        6
13.00        5
11.00        4
20.00        4
16.00        4
9.00         4
18.00        3
999.00       2
14.00        2
25.00        1
24.00        1
Name: count, dtype: int64
------------------------------
Valores faltantes en Promedio_Tragos_Dia: 1


np.int64(1)

2 personas no saben cuanto beben al dia, las eliminaremos por simplicidad

In [327]:
df[df['Promedio_Tragos_Dia']==999]

,SEQN,ALQ101,ALQ110,Frec_Consumo_Anual,Unidad_Frec_Anual,Promedio_Tragos_Dia,Dias_4_5_Tragos,Unidad_4_5_Tragos,Dias_Con_+4_5_Tragos_En_2hrs,Consumio_Alcohol,Dias_Consumo_Anual
423,74284.00,1.00,NaN,2.00,3.00,999.00,0.00,NaN,NaN,True,2.00
1236,75774.00,1.00,NaN,1.00,1.00,999.00,0.00,NaN,NaN,True,52.00


In [328]:
# Filtramos el dataframe para excluir las filas con 999
df = df[df['Promedio_Tragos_Dia'] != 999]
# Filtramos el dataframe para excluir las filas con nulo
df = df.dropna(subset=['Promedio_Tragos_Dia'])
# Reseteamos el índice para mantener el orden
df = df.reset_index(drop=True)

In [329]:
analizar_columna(df,'Promedio_Tragos_Dia')

--- Resumen de: Promedio_Tragos_Dia ---

📊 Estadísticas Descriptivas:
count   5917.00
mean       1.63
std        2.26
min        0.00
25%        0.00
50%        1.00
75%        2.00
max       25.00
Name: Promedio_Tragos_Dia, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Promedio_Tragos_Dia
0.00     2327
1.00     1279
2.00     1002
3.00      535
4.00      282
6.00      156
5.00      154
8.00       54
12.00      43
10.00      28
7.00       23
15.00       6
13.00       5
16.00       4
11.00       4
20.00       4
9.00        4
18.00       3
14.00       2
25.00       1
24.00       1
Name: count, dtype: int64
------------------------------


### Limpieza Dias_4_5_Tragos

In [330]:
df['Dias_4_5_Tragos'] = df['Dias_4_5_Tragos'].round(2)

# Si alguien no bebio, ponemos 0
df.loc[df['Frec_Consumo_Anual'] == 0, 'Dias_4_5_Tragos'] = 0

analizar_columna(df,'Dias_4_5_Tragos')
contar_nulos(df,'Dias_4_5_Tragos')


--- Resumen de: Dias_4_5_Tragos ---

📊 Estadísticas Descriptivas:
count   5916.00
mean       2.30
std       33.00
min        0.00
25%        0.00
50%        0.00
75%        0.00
max      999.00
Name: Dias_4_5_Tragos, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Dias_4_5_Tragos
0.00      4446
1.00       450
2.00       364
3.00       171
4.00       107
5.00       101
10.00       69
7.00        50
6.00        39
12.00       17
30.00       17
8.00        17
20.00       13
15.00       10
999.00       6
14.00        4
9.00         4
25.00        3
24.00        3
350.00       2
40.00        2
100.00       2
16.00        2
21.00        1
150.00       1
78.00        1
13.00        1
45.00        1
18.00        1
60.00        1
52.00        1
11.00        1
305.00       1
96.00        1
72.00        1
17.00        1
62.00        1
104.00       1
61.00        1
50.00        1
Name: count, dtype: int64
------------------------------
Valores faltantes en Dias_4_5_Tragos: 1


np.int64(1)

In [331]:
df[df['Dias_4_5_Tragos']== 777]

,SEQN,ALQ101,ALQ110,Frec_Consumo_Anual,Unidad_Frec_Anual,Promedio_Tragos_Dia,Dias_4_5_Tragos,Unidad_4_5_Tragos,Dias_Con_+4_5_Tragos_En_2hrs,Consumio_Alcohol,Dias_Consumo_Anual


In [332]:
df[df['Dias_4_5_Tragos']== 999]

,SEQN,ALQ101,ALQ110,Frec_Consumo_Anual,Unidad_Frec_Anual,Promedio_Tragos_Dia,Dias_4_5_Tragos,Unidad_4_5_Tragos,Dias_Con_+4_5_Tragos_En_2hrs,Consumio_Alcohol,Dias_Consumo_Anual
799,74982.00,1.00,NaN,5.00,2.00,2.00,999.00,NaN,0.00,True,60.00
1654,76488.00,1.00,NaN,2.00,1.00,8.00,999.00,NaN,NaN,True,104.00
2336,77640.00,1.00,NaN,3.00,3.00,6.00,999.00,NaN,0.00,True,3.00
2376,77702.00,2.00,1.00,5.00,2.00,3.00,999.00,NaN,NaN,True,60.00
4409,81122.00,1.00,NaN,3.00,2.00,2.00,999.00,NaN,0.00,True,36.00
5887,83687.00,1.00,NaN,3.00,2.00,1.00,999.00,NaN,1.00,True,36.00


In [333]:
df[df['Dias_4_5_Tragos'].isna()]

,SEQN,ALQ101,ALQ110,Frec_Consumo_Anual,Unidad_Frec_Anual,Promedio_Tragos_Dia,Dias_4_5_Tragos,Unidad_4_5_Tragos,Dias_Con_+4_5_Tragos_En_2hrs,Consumio_Alcohol,Dias_Consumo_Anual
853,75093.00,1.00,NaN,1.00,1.00,5.00,NaN,NaN,NaN,True,52.00


In [334]:
df = df.dropna(subset=['Dias_4_5_Tragos'])
df = df[df['Dias_4_5_Tragos'] != 999]
df = df.reset_index(drop=True)

### Limpieza Unidad_4_5_Tragos

In [335]:
df.loc[df['Dias_4_5_Tragos'] == 0, 'Unidad_4_5_Tragos'] = 0

analizar_columna(df,'Unidad_4_5_Tragos')
contar_nulos(df,'Unidad_4_5_Tragos')

# Si no tomo 4-5 tragos en un dia, su unidad es 0

df


--- Resumen de: Unidad_4_5_Tragos ---

📊 Estadísticas Descriptivas:
count   5910.00
mean       0.58
std        1.09
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        3.00
Name: Unidad_4_5_Tragos, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Unidad_4_5_Tragos
0.00    4446
3.00     839
1.00     361
2.00     264
Name: count, dtype: int64
------------------------------
Valores faltantes en Unidad_4_5_Tragos: 0


,SEQN,ALQ101,ALQ110,Frec_Consumo_Anual,Unidad_Frec_Anual,Promedio_Tragos_Dia,Dias_4_5_Tragos,Unidad_4_5_Tragos,Dias_Con_+4_5_Tragos_En_2hrs,Consumio_Alcohol,Dias_Consumo_Anual
0,73557.00,1.00,NaN,1.00,3.00,1.00,0.00,0.00,NaN,True,1.00
1,73558.00,1.00,NaN,7.00,1.00,4.00,2.00,1.00,0.00,True,364.00
2,73559.00,1.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,False,0.00
3,73561.00,1.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,False,0.00
4,73562.00,1.00,NaN,5.00,3.00,1.00,0.00,0.00,0.00,True,5.00
...,...,...,...,...,...,...,...,...,...,...,...
5905,83723.00,1.00,NaN,3.00,3.00,2.00,0.00,0.00,NaN,True,3.00
5906,83724.00,1.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,False,0.00
5907,83726.00,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,False,0.00
5908,83727.00,1.00,NaN,1.00,2.00,3.00,0.00,0.00,NaN,True,12.00


# todo: dias_alto_consumo
juntar Dias y Unidad

### Limpiar Dias_Con_+4_5_Tragos_En_2hrs

In [336]:
analizar_columna(df,'Dias_Con_+4_5_Tragos_En_2hrs')
contar_nulos(df,'Dias_Con_+4_5_Tragos_En_2hrs')

--- Resumen de: Dias_Con_+4_5_Tragos_En_2hrs ---

📊 Estadísticas Descriptivas:
count   4055.00
mean       0.56
std       15.77
min        0.00
25%        0.00
50%        0.00
75%        0.00
max      999.00
Name: Dias_Con_+4_5_Tragos_En_2hrs, dtype: float64

🔢 Conteo de Valores (Frecuencias):
Dias_Con_+4_5_Tragos_En_2hrs
0.00      3649
1.00       169
2.00       111
3.00        38
4.00        26
5.00        13
10.00       10
8.00         7
6.00         6
7.00         5
30.00        5
12.00        3
20.00        3
15.00        3
13.00        2
9.00         2
25.00        1
14.00        1
999.00       1
Name: count, dtype: int64
------------------------------
Valores faltantes en Dias_Con_+4_5_Tragos_En_2hrs: 1855


np.int64(1855)

In [337]:
# si no tienes un dia con 4/5 tragos, marcar 0 
df.loc[df['Dias_4_5_Tragos'] == 0, 'Dias_Con_+4_5_Tragos_En_2hrs'] = 0


In [338]:
df

,SEQN,ALQ101,ALQ110,Frec_Consumo_Anual,Unidad_Frec_Anual,Promedio_Tragos_Dia,Dias_4_5_Tragos,Unidad_4_5_Tragos,Dias_Con_+4_5_Tragos_En_2hrs,Consumio_Alcohol,Dias_Consumo_Anual
0,73557.00,1.00,NaN,1.00,3.00,1.00,0.00,0.00,0.00,True,1.00
1,73558.00,1.00,NaN,7.00,1.00,4.00,2.00,1.00,0.00,True,364.00
2,73559.00,1.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,False,0.00
3,73561.00,1.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,False,0.00
4,73562.00,1.00,NaN,5.00,3.00,1.00,0.00,0.00,0.00,True,5.00
...,...,...,...,...,...,...,...,...,...,...,...
5905,83723.00,1.00,NaN,3.00,3.00,2.00,0.00,0.00,0.00,True,3.00
5906,83724.00,1.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,False,0.00
5907,83726.00,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,False,0.00
5908,83727.00,1.00,NaN,1.00,2.00,3.00,0.00,0.00,0.00,True,12.00


In [339]:
df = df.drop(columns=['ALQ101','ALQ110'])


In [340]:
df.to_csv('../data/alq.csv', index=False)